---
version: "2.1"
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - ${HOME}/Projects/smokeping-ffs/config:/config
      - ${HOME}/Projects/smokeping-ffs/data:/data
    ports:
      - 80:80
    restart: unless-stopped